#############################################################################
# Makefile for building: coltura-batterica
# Generated by qmake (2.01a) (Qt 4.8.2) on: ven ago 24 15:29:04 2012
# Project:  coltura-batterica.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt/mkspecs/linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug -o Makefile coltura-batterica.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1,--sort-common,--as-needed,-z,relro
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		coltura.cpp \
		pilamatrici.cpp \
		pilamatrici_IO.cpp \
		starter.cpp \
		popup.cpp \
		debug.cpp moc_mainwindow.cpp \
		moc_coltura.cpp \
		moc_starter.cpp \
		moc_popup.cpp \
		moc_debug.cpp
OBJECTS       = main.o \
		mainwindow.o \
		coltura.o \
		pilamatrici.o \
		pilamatrici_IO.o \
		starter.o \
		popup.o \
		debug.o \
		moc_mainwindow.o \
		moc_coltura.o \
		moc_starter.o \
		moc_popup.o \
		moc_debug.o
DIST          = /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/declarative_debug.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		coltura-batterica.pro
QMAKE_TARGET  = coltura-batterica
DESTDIR       = 
TARGET        = coltura-batterica

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: coltura-batterica.pro  /usr/share/qt/mkspecs/linux-g++-64/qmake.conf /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/declarative_debug.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug -o Makefile coltura-batterica.pro
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/common/gcc-base.conf:
/usr/share/qt/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt/mkspecs/common/g++-base.conf:
/usr/share/qt/mkspecs/common/g++-unix.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/modules/qt_phonon.pri:
/usr/share/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/debug.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/declarative_debug.prf:
/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug -o Makefile coltura-batterica.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/coltura-batterica1.0.0 || $(MKDIR) .tmp/coltura-batterica1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/coltura-batterica1.0.0/ && $(COPY_FILE) --parents mainwindow.h main.h coltura.h pilamatrici.h errors.h starter.h popup.h debug.h .tmp/coltura-batterica1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp coltura.cpp pilamatrici.cpp pilamatrici_IO.cpp starter.cpp popup.cpp debug.cpp .tmp/coltura-batterica1.0.0/ && (cd `dirname .tmp/coltura-batterica1.0.0` && $(TAR) coltura-batterica1.0.0.tar coltura-batterica1.0.0 && $(COMPRESS) coltura-batterica1.0.0.tar) && $(MOVE) `dirname .tmp/coltura-batterica1.0.0`/coltura-batterica1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/coltura-batterica1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_coltura.cpp moc_starter.cpp moc_popup.cpp moc_debug.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_coltura.cpp moc_starter.cpp moc_popup.cpp moc_debug.cpp
moc_mainwindow.cpp: coltura.h \
		pilamatrici.h \
		mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_coltura.cpp: pilamatrici.h \
		coltura.h
	/usr/bin/moc $(DEFINES) $(INCPATH) coltura.h -o moc_coltura.cpp

moc_starter.cpp: mainwindow.h \
		coltura.h \
		pilamatrici.h \
		starter.h
	/usr/bin/moc $(DEFINES) $(INCPATH) starter.h -o moc_starter.cpp

moc_popup.cpp: popup.h
	/usr/bin/moc $(DEFINES) $(INCPATH) popup.h -o moc_popup.cpp

moc_debug.cpp: debug.h
	/usr/bin/moc $(DEFINES) $(INCPATH) debug.h -o moc_debug.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		coltura.h \
		pilamatrici.h \
		starter.h \
		main.h \
		errors.h \
		popup.h \
		debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp main.h \
		errors.h \
		mainwindow.h \
		coltura.h \
		pilamatrici.h \
		starter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

coltura.o: coltura.cpp main.h \
		errors.h \
		coltura.h \
		pilamatrici.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o coltura.o coltura.cpp

pilamatrici.o: pilamatrici.cpp pilamatrici.h \
		main.h \
		errors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pilamatrici.o pilamatrici.cpp

pilamatrici_IO.o: pilamatrici_IO.cpp main.h \
		errors.h \
		pilamatrici.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pilamatrici_IO.o pilamatrici_IO.cpp

starter.o: starter.cpp starter.h \
		mainwindow.h \
		coltura.h \
		pilamatrici.h \
		main.h \
		errors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o starter.o starter.cpp

popup.o: popup.cpp popup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o popup.o popup.cpp

debug.o: debug.cpp debug.h \
		main.h \
		errors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug.o debug.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_coltura.o: moc_coltura.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_coltura.o moc_coltura.cpp

moc_starter.o: moc_starter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_starter.o moc_starter.cpp

moc_popup.o: moc_popup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_popup.o moc_popup.cpp

moc_debug.o: moc_debug.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_debug.o moc_debug.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

